name: motunge
description: "모퉁이 공식 앱 ✨"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^15.1.1
  flutter_naver_map: ^1.3.1
  geolocator: ^14.0.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env

flutter_native_splash:
  color: "#125CED"
  image: assets/images/logo.png
  android: true
  android_12:
    image: assets/images/logo_android.png
  ios: true
