name: motunge
description: "모퉁이 공식 앱 ✨"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_native_splash:
  color: "#125CED"
  image: assets/images/logo.png
  android: true
  android_12:
    image: assets/images/logo_android.png
  ios: true
